### ISSUE TITLE
Is the code of lambda_rbp() in lamda_loss.py unfinfised?

### ISSUE THREAD

**Issue by YuehuaZhu** [roger-zhe-li/sigir21-newinsights#1]
Hello, thanks for sharing the code. Is the code of lambda_rbp() in lamda_loss.py unfinfised?

**Comment by roger-zhe-li** [comment]
Hi Yuehua,

Thanks for pointing out. Indeed, the last code snippet for lambda_rbp loss was missing. This was because I put the dev file into the repo. Now it has been added. Please note that the change also happened to the lambda nDCG function, since the dev file was also incorrect in this place. Thanks again.
